In [1]:
pip install hummingbird-ml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.6/164.6 KB 4.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 KB 7.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.8/83.8 KB 7.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 KB 3.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 39.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 39.8 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.6
    Uninstalling protobuf-3.19.6:
      Successfully uninstalled protobuf-3.19.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 w

In [3]:
#1. Simple classification problem which we are trying to solve with random classifier. 
#2. Then we will convert this modle into pytorch model.
#3. Then we will predict for some the data 
#4. Then we will check how much time is it actually taking. 

In [5]:
pip install -U scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from hummingbird.ml import convert

#Create some random data for binary classification 
num_classes = 2
X = np.array(np.random.rand(100000, 28), dtype=np.float32)
y = np.random.randint(num_classes, size=100000)

In [10]:
X

array([[0.09149725, 0.0242525 , 0.12062229, ..., 0.303704  , 0.3523725 ,
        0.3288384 ],
       [0.59744215, 0.6059796 , 0.8143251 , ..., 0.23970255, 0.7704873 ,
        0.12658672],
       [0.579345  , 0.87101233, 0.56574947, ..., 0.6852788 , 0.23145309,
        0.2569434 ],
       ...,
       [0.31399056, 0.0878107 , 0.00947927, ..., 0.0669785 , 0.20881793,
        0.4768961 ],
       [0.06100375, 0.31021714, 0.03399121, ..., 0.65288776, 0.05905779,
        0.08584499],
       [0.48341453, 0.36687905, 0.09052496, ..., 0.9724122 , 0.3467944 ,
        0.87213147]], dtype=float32)

In [11]:
X,y

(array([[0.09149725, 0.0242525 , 0.12062229, ..., 0.303704  , 0.3523725 ,
         0.3288384 ],
        [0.59744215, 0.6059796 , 0.8143251 , ..., 0.23970255, 0.7704873 ,
         0.12658672],
        [0.579345  , 0.87101233, 0.56574947, ..., 0.6852788 , 0.23145309,
         0.2569434 ],
        ...,
        [0.31399056, 0.0878107 , 0.00947927, ..., 0.0669785 , 0.20881793,
         0.4768961 ],
        [0.06100375, 0.31021714, 0.03399121, ..., 0.65288776, 0.05905779,
         0.08584499],
        [0.48341453, 0.36687905, 0.09052496, ..., 0.9724122 , 0.3467944 ,
         0.87213147]], dtype=float32), array([1, 0, 0, ..., 1, 1, 1]))

In [12]:
#Creating and training random forrest classifier 
skl_model = RandomForestClassifier(n_estimators=10, max_depth=10)
skl_model.fit(X,y)

RandomForestClassifier(max_depth=10, n_estimators=10)

In [13]:
# Use Hummingbird to convert the model to pyTorch
model = convert(skl_model, 'pytorch')

In [14]:
%%timeit -r 3
# Run Hummingbord on CPU - By default CPU execution is used in Hummingbird. 
model.predict(X)

242 ms ± 80.1 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)


In [15]:
%%time 
#Run predictions on GPU
model.to("cuda")
model.predict(X)

CPU times: user 1.19 s, sys: 1.26 s, total: 2.45 s
Wall time: 5.08 s


array([0, 1, 1, ..., 0, 1, 0])